# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_group_controller
    - gripper_group_controller

  arm_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - joint2
      - joint3
      - joint4
      - joint5
  gripper_group_controller:
    type: GripperCommand
    joints:
      - r_joint
    action_ns: gripper_cmd
    default: true