# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true
    # 注意，以下控制器需要启动时主动显式加载 & 激活 ros2 control load_controller <name> --set-state active
    # 力控 控制器
    vbot_effort_controller:
      type: effort_controllers/JointGroupEffortController
    # 注意：力控和两轮差速控制器不建议同时激活（但可以同时加载）
    # 力控只建议在精细操作时使用，这里下面的参数填的是轮子，仅作示例使用
    # vbot_diff_drive_controller:
    #   type: diff_drive_controller/DiffDriveController
    vbot_ackermann_steering_controller:
      type: 'ackermann_steering_controller/AckermannSteeringController'
      use_sim_time: true

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      use_sim_time: true


    gripper_group_controller:
      type: position_controllers/GripperActionController
      use_sim_time: true


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      use_sim_time: true


joint_state_broadcaster:
  ros__parameters:
    # extra_joints: '{}'
    frame_id: base_footprint
    # interfaces: '{}'
    # joints: '{}'
    map_interface_to_joint_state:
      effort: effort
      position: position
      velocity: velocity
    use_local_topics: false
    use_urdf_to_filter: true

vbot_effort_controller:
  ros__parameters:
    joints:
      - wheel_left_back_joint
      - wheel_right_back_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

# https://control.ros.org/jazzy/doc/ros2_controllers/ackermann_steering_controller/doc/userdoc.html
vbot_ackermann_steering_controller:
  ros__parameters:
    reference_timeout: 2.0
    traction_joints_names: ["wheel_right_back_joint", "wheel_left_back_joint"]
    steering_joints_names: ["right_steering_joint", "left_steering_joint"]
    open_loop: false
    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: true
    velocity_rolling_window_size: 10
    wheelbase: 0.214
    steering_track_width: 0.184
    traction_track_width: 0.184
    traction_wheels_radius: 0.05

arm_group_controller:
  ros__parameters:
    joints:
      - joint2
      - joint3
      - joint4
      - joint5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
gripper_group_controller:
  ros__parameters:
    joint: r_joint