sensors:
  - default_sensor
default_sensor:
  far_clipping_plane_distance: 10
  filtered_cloud_topic: ""
  image_topic: camera/rgbd/depth_image
  max_update_rate: 30
  near_clipping_plane_distance: 0.1
  padding_offset: ""
  padding_scale: ""
  queue_size: ""
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  shadow_threshold: ""